name: 'Deploy to S3'
description: 'Deploy to S3 and make my website live'
inputs:
  bucketName:
    description: 'Bucket name to deploy to S3'
    required: true

  bucketRegion:
    description: 'Bucket region to deploy to S3'
    required: false
    default: 'us-east-1'

  distFiles:
    description: 'Artifacts to deploy to S3'
    required: true

outputs:
  url:
    description: 'URL of the deployed website'

runs:
  using: 'node22'
  main: 'index.js'
 
